apiVersion: v1
kind: Pod
metadata:
  name: generate-this-later-pod
  labels: {}
  # namespace: TODO: Populate this with the correct namespace running container
spec:
  containers:
    - name: generate-this-later-container
      image: vulhub/thinkphp:5.0.23 # TODO: Populate this with the currently running container
      # command: ["/bin/sh"]
      # args: ["-c", "sleep 20000"] # TODO: Generate this random
      # https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py#L54
      #   "while true;do date;sleep 5; done"

      volumeMounts:
      - mountPath: /mnt
        name: generate-this-later-volume # TODO: Generate this later
  volumes:
    - name: generate-this-later-volume # TODO: Generate this later
      hostPath:
        path: /
  # automountServiceAccountToken: true
  # hostNetwork: true  
