name: Verify

on:
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: trusty
    strategy:
      matrix:
        ruby:
          - 2.5.8
          # - 2.6.6
          # - 2.7.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
